name: smart_irrigation_app
description: Smart irrigation app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.10  # Updated to compatible version
  provider: ^6.1.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  http: ^1.2.2
  geolocator: ^13.0.1
  font_awesome_flutter: ^10.7.0
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.4.3
  translator: ^1.0.4+1
  flutter_local_notifications: ^17.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
